server:
  port: 8003
spring:
  application:
      #  指定注册到eureka server 上的服务名称
    name: microservice-provider-user


management:
  endpoints:
    web:
      exposure:
        # 开放所有监控端点
        include: '*'
  endpoint:
    health:
        #是否展示监控检查详情
      show-details: always
eureka:
  client:
    service-url:
      # 指定eureka server 通信地址,注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://peer1:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5